language: java
jdk:
 - oraclejdk8
before_install:
  -  chmod +x ./travis/*
  - ./travis/install-mysql.sh
  - ./travis/mysql-reset-root-password.sh
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: cfs-1